name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: "1 0,6,12,18 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Install clippy
        run: rustup component add clippy
      - name: Build
        run: |
          cargo version
          cargo build --verbose
      - name: Run clippy
        run: |
          cargo clippy -- -D warnings
